version: 2

jobs:
  build:
    working_directory: ~/orthopy
    docker:
      - image: ubuntu:18.04
    steps:
      - run: apt update
      - run: apt install -y git python3-pip gmsh
      - run: pip3 install -U pytest pytest-cov pylint
      - checkout
      - run: pip3 install .[all]
      - run: pip3 install -r test_requirements.txt
      # lint
      - run: pylint setup.py orthopy/ test/*.py
      # The tests
      - run: cd test/ && MPLBACKEND=Agg pytest --cov orthopy
      # submit to codecov
      - run: apt install -y curl
      - run: bash <(curl -s https://codecov.io/bash)
